<a href="https://colab.research.google.com/github/EduardoMauricio1/Practicas-Quimica/blob/main/Copia_de_Ejercicios_de_repado_G8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Crea una lista de 10 números e imprime los valores negativos en otra lista

In [2]:
type([1,2,3,4,5,6,7,8,9,10])

list

In [4]:
[1,2,3,4,5,6,7,8,9,10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
import numpy as np

In [28]:
numeros = np.random.randint(1,20,size=10)


In [24]:
len(numeros)

10

In [29]:
numeros

array([10, 19, 15, 11,  1,  1, 13,  4,  5, 18])

In [41]:
# [Lo que quiero | Como lo voy a generar]
numeros_negativos = [x*-1 for x in numeros]

In [42]:
numeros_negativos

[-10, -19, -15, -11, -1, -1, -13, -4, -5, -18]

# 2. Escribe una matriz de 3x3 con números float distintos

In [52]:
matriz = [[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]]

In [53]:
type[[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]]


type[[1.1, 2.2, 3.3], [4.4, 5.5, 6.6], [7.7, 8.8, 9.9]]

In [54]:
np.random.random_sample((3,3))

array([[0.85073722, 0.56331865, 0.42245025],
       [0.3781665 , 0.7160918 , 0.94136895],
       [0.99558199, 0.50035474, 0.22984381]])

# 3. Crea una matriz A de 3x3 y 2 matrices (B y C) de 3x1 con números enteros distintos y calcula AxB+C

In [67]:
A = np.random.random_sample((3,3))

In [65]:
B = np.random.random_sample((3,1))

In [66]:
C = np.random.random_sample((3,1))

In [72]:
A.shape, B.shape, C.shape

((3, 3), (3, 1), (3, 1))

In [76]:
#La siguiente no es una operacion entre matricez
((A*B)+C)

array([[0.36010041, 0.35891646, 0.35929658],
       [0.4170038 , 0.46437643, 0.41459446],
       [1.01409001, 0.80725934, 0.79174329]])

In [75]:
#La siguiente su es una operacion entre matricez
A@B*C

array([[0.20265292],
       [0.05190784],
       [0.24864312]])

# 4. Disponer de números enteros desde el 1 hasta el 100 y cambiar los múltiplos de 3 por el string “m3”

In [ ]:
np.linspace(1,100,100)

In [88]:
arreglo = np.arange(1,101)
arreglo

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [87]:
len(arreglo)

100

In [90]:
arreglo%3

array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1])

In [101]:
#Llamar un elemento
arreglo[2]

3

In [104]:
if arreglo[2]%3==0:
  print('hola')
else:
  print('adios')

hola


In [ ]:
for valor in arreglo:
  if arreglo[valor-1]%3==0:
    print(valor)
  else:
    print('adios')

In [110]:
#Append
lista_valores = []

for valor in arreglo:
  if arreglo[valor-1]%3==0:
    lista_valores.append('m3')
  else:
    lista_valores.append(valor)

In [ ]:
lista_valores

In [ ]:
["m3" if i%3==0 else i for i in range(1,101)]

# 5. Recorriendo la matriz A del ejercicio 3, calcular la traza de la matriz transpuesta

In [113]:
A

array([[0.73309647, 0.71059661, 0.71782048],
       [0.80025984, 0.90924905, 0.79471671],
       [0.95297043, 0.42806848, 0.3886913 ]])

In [118]:
A[0][0] + A[1][1] + A[2][2]

2.0310368247738655

In [127]:
#Imprime la diagonal
for indice, numero in enumerate(A):
  print(numero[indice])

0.7330964672991991
0.909249054646862
0.3886913028278044


In [ ]:
milista = []

for indice, numero in enumerate(A):
  milista.append(numero[indice])
  #print(numero[indice])

In [132]:
sum(milista)

12

# 6. Encuentra un autovalor y su autovector, para la matriz D. Puedes ayudarte multiplicando D con las matrices de 2x1 E, F y G

Si:

D = np.array([[3, 2], [1, 4]])

E = np.array([[1,0]])

F = np.array([[0,1]])

G = np.array([[1,1]])